name: Trigger Deploy Terraform 

on:
  push:
    branches:
      - main

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_DISPATCH_TOKEN }}
        repository: yesaswi/test-serverless-cd
        event-type: deploy-function
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
