name: Trigger Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_DISPATCH_TOKEN }}
        repository: 'https://github.com/yesaswi/test-serverless-cd'
        event-type: deploy-function
